# Generated by Django 4.2.18 on 2025-01-29 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do cliente')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da venda')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do produto')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Produto vendido',
                'verbose_name_plural': 'Produtos vendidos',
            },
        ),
    ]
