# Generated by Django 4.2.18 on 2025-02-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_venda_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
